alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pkaselj-simplegermanflaskquiz
    match:
      path:
        prefix: /
name: simple-german-quiz
region: fra
services:
- http_port: 80
  image:
    registry: pkaselj
    registry_type: GHCR
    repository: simplegermanflaskquiz
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pkaselj-simplegermanflaskquiz