name: Docker Image CI

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simple-german-quiz:$GITHUB_REF_NAME_$(date +%s)
