name: Build, Push and Deploy a Docker Image

on:
 push:
   tags: ['*']

permissions:
  contents: read
  packages: write

jobs:
 build-push-deploy-image:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Log in to the Container registry
       uses: docker/login-action@v3.3.0
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - id: lowercase_repo
       name: Change String Case
       uses: ASzc/change-string-case-action@v6
       with:
          string: ${{ github.repository }}
     - name: Build and push Docker image
       id: push
       uses: docker/build-push-action@v6.5.0
       with:
         context: .
         push: true
         tags: ghcr.io/${{ steps.lowercase_repo.outputs.lowercase }}:latest
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       env:
         SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
       with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         print_build_logs: true
         print_deploy_logs: true